color0 #44474c
color1 #ffb4ab
color2 #bdc7da
color3 #c4c6cf
color4 #d6c0d5
color5 #bdc7da
color6 #c4c6cf
color7 #e4e2e3
color8 #8f9096
color9 #ffb4ab
color10 #bdc7da
color11 #c4c6cf
color12 #d6c0d5
color13 #bdc7da
color14 #c4c6cf
color15 #e4e2e3

cursor                #e4e2e3
cursor_text_color     #131314
background            #131314
foreground            #e4e2e3
selection_foreground  #c5c6cc
selection_background  #44474c
active_border_color   #bdc7da
inactive_border_color #44474c
url_color             #bdc7da

active_tab_foreground   #273140
active_tab_background   #bdc7da
inactive_tab_foreground #c5c6cc
inactive_tab_background #44474c
cursor_trail_color      #c5c6cc
